version: "3.9"
services:
    miner:
        build: ./miner
        expose:
            - "8000"
        deploy:
            resources:
                limits:
                    cpus: '64'
    nginx:
        build: ./nginx
        ports:
            - "8000:8000"
